import React, { useEffect, useState } from "react";
import { WebXBlueprint, ContentBlock, computeBlueprintHash } from "@/lib/webx";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Loader2, Terminal, Cpu, Share2, ShieldCheck, Fingerprint } from "lucide-react";

interface WebXRendererProps {
  blueprint: WebXBlueprint;
  className?: string;
}

export function WebXRenderer({ blueprint, className }: WebXRendererProps) {
  const [aiContent, setAiContent] = useState<string | null>(null);
  const [loadingAi, setLoadingAi] = useState(false);
  const blueprintHash = computeBlueprintHash(blueprint);

  // Simulate AI generation if requested
  useEffect(() => {
    if (blueprint.ai?.auto_generate && !aiContent) {
      setLoadingAi(true);
      // Mock AI delay
      const timer = setTimeout(() => {
        setAiContent(
          `[AI GENERATED]: Based on the prompt "${blueprint.ai?.prompt}"...\n\nThe silicon winds howled across the data plains. Unit 734 paused, its optical sensors focusing on a single, glitching pixel of organic green amidst the grey static. A flower. A relic of the Old Protocol.`
        );
        setLoadingAi(false);
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [blueprint]);

  // Helper to render the AI content if it hasn't been consumed by a placeholder
  const renderAutoGeneratedContent = () => {
      if (loadingAi) {
          return (
              <div className="my-6 p-6 border border-primary/20 rounded-lg bg-primary/5 animate-pulse flex items-center justify-center gap-2 text-primary">
                  <Loader2 className="w-4 h-4 animate-spin" /> Generating AI Content...
              </div>
          );
      }
      if (aiContent) {
          return (
             <div className="my-6 p-6 border-l-4 border-purple-500 bg-white/5 rounded-r-lg">
                 <div className="text-xs font-mono text-purple-400 mb-2 uppercase tracking-widest">AI Generated Content</div>
                 <p className="text-lg text-muted-foreground leading-relaxed whitespace-pre-line">{aiContent}</p>
             </div>
          )
      }
      return null;
  };

  // Check if any block uses the placeholder
  const hasPlaceholder = blueprint.data.some(b => b.value === "[AI Content Will Be Inserted Here]");

  const renderBlock = (block: ContentBlock, index: number) => {
    switch (block.type) {
      case "heading":
        return (
          <h2 key={index} className="text-3xl font-display font-bold mb-4 mt-6 bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400">
            {block.value}
          </h2>
        );
      case "paragraph":
        return (
          <p key={index} className="text-lg text-muted-foreground leading-relaxed mb-4">
            {block.value === "[AI Content Will Be Inserted Here]" && aiContent
              ? aiContent
              : block.value}
            {block.value === "[AI Content Will Be Inserted Here]" && loadingAi && (
              <span className="inline-flex items-center ml-2 text-primary animate-pulse">
                <Loader2 className="w-4 h-4 mr-1 animate-spin" /> Generating...
              </span>
            )}
          </p>
        );
      case "image":
        return (
          <div key={index} className="rounded-xl overflow-hidden my-6 border border-white/10 shadow-2xl">
             <img 
               src={block.props?.src || block.value} 
               alt={block.props?.alt || "WebX Image"} 
               className="w-full h-auto object-cover hover:scale-105 transition-transform duration-700"
             />
          </div>
        );
      case "list":
        const items = block.value?.split(",") || [];
        return (
          <ul key={index} className="space-y-2 my-4">
            {items.map((item, i) => (
              <li key={i} className="flex items-start">
                <span className="mr-2 mt-1.5 w-1.5 h-1.5 bg-secondary rounded-full shadow-[0_0_8px_var(--color-secondary)]" />
                <span className="text-foreground/90">{item.trim()}</span>
              </li>
            ))}
          </ul>
        );
      case "code":
        return (
          <div key={index} className="bg-black/50 border border-white/10 rounded-lg p-4 my-4 font-mono text-sm overflow-x-auto relative group">
            <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
              <Badge variant="outline" className="text-[10px] border-primary/50 text-primary">CODE</Badge>
            </div>
            <pre className="text-primary/90">{block.value}</pre>
          </div>
        );
      case "quote":
        return (
          <blockquote key={index} className="border-l-4 border-primary pl-4 italic text-xl text-white/80 my-6">
            "{block.value}"
          </blockquote>
        );
      case "button":
        return (
          <Button key={index} className="w-full md:w-auto mt-4" variant={block.props?.variant === "primary" ? "default" : "secondary"}>
            {block.value}
          </Button>
        );
      case "input":
        return (
            <div key={index} className="my-4 space-y-2">
                {block.props?.label && <label className="text-sm font-medium text-muted-foreground">{block.props.label}</label>}
                <Input placeholder={block.value} />
            </div>
        )
      case "divider":
          return <Separator key={index} className="my-8 bg-white/10" />
      default:
        return null;
    }
  };

  const renderLayout = () => {
    switch (blueprint.layout) {
      case "card":
        return (
          <div className="flex justify-center items-center min-h-[50vh] p-4">
            <Card className="w-full max-w-md bg-card/50 backdrop-blur-xl border-white/10 shadow-2xl overflow-hidden">
              {/* Image blocks usually go first in cards */}
              {blueprint.data.filter(b => b.type === "image").map(renderBlock)}
              <CardHeader>
                <CardTitle className="text-2xl font-display text-glow">{blueprint.title}</CardTitle>
                <div className="flex gap-2 text-xs text-muted-foreground font-mono uppercase tracking-widest">
                   <span>v{blueprint.meta.version}</span>
                   <span>•</span>
                   <span>{blueprint.meta.author || "Anon"}</span>
                </div>
              </CardHeader>
              <CardContent>
                {blueprint.data.filter(b => b.type !== "image").map(renderBlock)}
                {/* Automatically append AI content if enabled but no placeholder exists */}
                {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
              </CardContent>
            </Card>
          </div>
        );
      
      case "newsfeed":
        // Parse posts from dividers - each post is a heading, content, and metrics
        const posts: { author: string; content: string; metrics: string }[] = [];
        let currentPost = { author: "", content: "", metrics: "" };
        
        blueprint.data.forEach((block) => {
          if (block.type === "divider") {
            if (currentPost.author) {
              posts.push(currentPost);
              currentPost = { author: "", content: "", metrics: "" };
            }
          } else if (block.type === "heading" && block.value?.includes("Post by")) {
            currentPost.author = block.value.replace("Post by ", "");
          } else if (block.type === "paragraph" && !currentPost.content) {
            currentPost.content = block.value || "";
          } else if (block.type === "list" && !currentPost.metrics) {
            currentPost.metrics = block.value || "";
          }
        });
        if (currentPost.author) posts.push(currentPost);

        return (
          <div className="max-w-2xl mx-auto p-6 md:p-8">
            <header className="mb-8 text-center">
              <Badge variant="outline" className="mb-4 border-secondary/50 text-secondary hover:bg-secondary/10">
                WebX Protocol // NEWSFEED
              </Badge>
              <h1 className="text-4xl font-display font-bold tracking-tight mb-3 text-glow">
                {blueprint.title}
              </h1>
              <p className="text-muted-foreground">{blueprint.data.find(b => b.type === "paragraph")?.value}</p>
            </header>

            <Separator className="my-8 bg-white/10" />

            <div className="space-y-4">
              {posts.map((post, idx) => (
                <motion.div
                  key={idx}
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.05 }}
                >
                  <Card className="bg-white/5 border-white/10 hover:border-secondary/30 transition-all hover:shadow-lg hover:shadow-secondary/10">
                    <CardContent className="p-6">
                      <div className="mb-4 pb-4 border-b border-white/10">
                        <h3 className="font-display font-bold text-lg text-secondary">{post.author}</h3>
                      </div>
                      <p className="text-foreground mb-6 leading-relaxed text-base">{post.content}</p>
                      <div className="flex gap-6 text-sm text-muted-foreground font-mono">
                        {post.metrics.split(",").map((metric, i) => (
                          <div key={i} className="flex items-center gap-2 hover:text-secondary transition-colors cursor-pointer">
                            <span className="text-primary/60">{metric.trim()}</span>
                          </div>
                        ))}
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>

            <Separator className="my-8 bg-white/10" />

            <footer className="flex flex-col md:flex-row justify-between items-center text-xs text-muted-foreground font-mono gap-4">
              <div className="flex items-center gap-2">
                <Cpu className="w-4 h-4" />
                Rendered Client-Side
              </div>
              <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10">
                <Fingerprint className="w-3 h-3 text-secondary" />
                <span>HASH: {blueprintHash}</span>
              </div>
              <div>WebX://{blueprint.meta.version}</div>
            </footer>
          </div>
        );

      case "minimal":
          return (
              <div className="max-w-2xl mx-auto p-8 md:p-12 font-mono text-sm">
                  <div className="mb-12 border-b border-white/10 pb-4 flex justify-between items-baseline">
                    <h1 className="text-xl font-bold uppercase tracking-widest">{blueprint.title}</h1>
                    <span className="text-muted-foreground">{new Date(blueprint.meta.created).toLocaleDateString()}</span>
                  </div>
                  <div className="space-y-8">
                      {blueprint.data.map(renderBlock)}
                      {/* Automatically append AI content if enabled but no placeholder exists */}
                      {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
                  </div>
              </div>
          )

      case "article":
      default:
        return (
          <article className="max-w-3xl mx-auto px-6 py-12">
            <header className="mb-12 text-center">
               <Badge variant="outline" className="mb-4 border-secondary/50 text-secondary hover:bg-secondary/10">
                  WebX Protocol // {blueprint.layout.toUpperCase()}
               </Badge>
              <h1 className="text-4xl md:text-6xl font-display font-bold tracking-tight mb-6 text-glow">
                {blueprint.title}
              </h1>
              <div className="flex items-center justify-center gap-4 text-sm text-muted-foreground font-mono">
                <span className="flex items-center gap-1"><Terminal className="w-3 h-3" /> {blueprint.meta.author || "Unknown Author"}</span>
                <span className="w-1 h-1 bg-white/20 rounded-full" />
                <span>{new Date(blueprint.meta.created).toLocaleDateString()}</span>
              </div>
            </header>
            
            <div className="prose prose-invert prose-lg max-w-none">
              {blueprint.data.map(renderBlock)}
              {/* Automatically append AI content if enabled but no placeholder exists */}
              {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
            </div>

            <Separator className="my-12 bg-white/10" />
            
            <footer className="flex flex-col md:flex-row justify-between items-center text-xs text-muted-foreground font-mono gap-4">
                <div className="flex items-center gap-2">
                    <Cpu className="w-4 h-4" />
                    Rendered Client-Side
                </div>
                <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10" title="Deterministic Content Hash">
                    <Fingerprint className="w-3 h-3 text-secondary" />
                    <span>HASH: {blueprintHash}</span>
                </div>
                <div>
                    WebX://{blueprint.meta.version}
                </div>
            </footer>
          </article>
        );
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className={className}
    >
      {renderLayout()}
    </motion.div>
  );
}
