import React, { useEffect, useState } from "react";
import { WebXBlueprint, ContentBlock, computeBlueprintHash } from "@/lib/webx";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Loader2, Terminal, Cpu, Share2, ShieldCheck, Fingerprint, Heart, MessageCircle, Repeat2, ChevronDown, ChevronUp, Send } from "lucide-react";

interface WebXRendererProps {
  blueprint: WebXBlueprint;
  className?: string;
}

interface PostData {
  id: string;
  author: string;
  content: string;
  likes: number;
  replies: number;
  shares: number;
  liked: boolean;
  expanded: boolean;
  comments: { author: string; text: string }[];
}

export function WebXRenderer({ blueprint, className }: WebXRendererProps) {
  const [aiContent, setAiContent] = useState<string | null>(null);
  const [loadingAi, setLoadingAi] = useState(false);
  const blueprintHash = computeBlueprintHash(blueprint);
  const [posts, setPosts] = useState<PostData[]>([]);
  const [newCommentText, setNewCommentText] = useState<{ [key: string]: string }>({});

  // Simulate AI generation if requested
  useEffect(() => {
    if (blueprint.ai?.auto_generate && !aiContent) {
      setLoadingAi(true);
      // Mock AI delay
      const timer = setTimeout(() => {
        setAiContent(
          `[AI GENERATED]: Based on the prompt "${blueprint.ai?.prompt}"...\n\nThe silicon winds howled across the data plains. Unit 734 paused, its optical sensors focusing on a single, glitching pixel of organic green amidst the grey static. A flower. A relic of the Old Protocol.`
        );
        setLoadingAi(false);
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [blueprint]);

  // Helper to render the AI content if it hasn't been consumed by a placeholder
  const renderAutoGeneratedContent = () => {
      if (loadingAi) {
          return (
              <div className="my-6 p-6 border border-primary/20 rounded-lg bg-primary/5 animate-pulse flex items-center justify-center gap-2 text-primary">
                  <Loader2 className="w-4 h-4 animate-spin" /> Generating AI Content...
              </div>
          );
      }
      if (aiContent) {
          return (
             <div className="my-6 p-6 border-l-4 border-purple-500 bg-white/5 rounded-r-lg">
                 <div className="text-xs font-mono text-purple-400 mb-2 uppercase tracking-widest">AI Generated Content</div>
                 <p className="text-lg text-muted-foreground leading-relaxed whitespace-pre-line">{aiContent}</p>
             </div>
          )
      }
      return null;
  };

  // Check if any block uses the placeholder
  const hasPlaceholder = blueprint.data.some(b => b.value === "[AI Content Will Be Inserted Here]");

  const renderBlock = (block: ContentBlock, index: number) => {
    switch (block.type) {
      case "heading":
        return (
          <h2 key={index} className="text-3xl font-display font-bold mb-4 mt-6 bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400">
            {block.value}
          </h2>
        );
      case "paragraph":
        return (
          <p key={index} className="text-lg text-muted-foreground leading-relaxed mb-4">
            {block.value === "[AI Content Will Be Inserted Here]" && aiContent
              ? aiContent
              : block.value}
            {block.value === "[AI Content Will Be Inserted Here]" && loadingAi && (
              <span className="inline-flex items-center ml-2 text-primary animate-pulse">
                <Loader2 className="w-4 h-4 mr-1 animate-spin" /> Generating...
              </span>
            )}
          </p>
        );
      case "image":
        return (
          <div key={index} className="rounded-xl overflow-hidden my-6 border border-white/10 shadow-2xl">
             <img 
               src={block.props?.src || block.value} 
               alt={block.props?.alt || "WebX Image"} 
               className="w-full h-auto object-cover hover:scale-105 transition-transform duration-700"
             />
          </div>
        );
      case "list":
        const items = block.value?.split(",") || [];
        return (
          <ul key={index} className="space-y-2 my-4">
            {items.map((item, i) => (
              <li key={i} className="flex items-start">
                <span className="mr-2 mt-1.5 w-1.5 h-1.5 bg-secondary rounded-full shadow-[0_0_8px_var(--color-secondary)]" />
                <span className="text-foreground/90">{item.trim()}</span>
              </li>
            ))}
          </ul>
        );
      case "code":
        return (
          <div key={index} className="bg-black/50 border border-white/10 rounded-lg p-4 my-4 font-mono text-sm overflow-x-auto relative group">
            <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
              <Badge variant="outline" className="text-[10px] border-primary/50 text-primary">CODE</Badge>
            </div>
            <pre className="text-primary/90">{block.value}</pre>
          </div>
        );
      case "quote":
        return (
          <blockquote key={index} className="border-l-4 border-primary pl-4 italic text-xl text-white/80 my-6">
            "{block.value}"
          </blockquote>
        );
      case "button":
        return (
          <Button key={index} className="w-full md:w-auto mt-4" variant={block.props?.variant === "primary" ? "default" : "secondary"}>
            {block.value}
          </Button>
        );
      case "input":
        return (
            <div key={index} className="my-4 space-y-2">
                {block.props?.label && <label className="text-sm font-medium text-muted-foreground">{block.props.label}</label>}
                <Input placeholder={block.value} />
            </div>
        )
      case "divider":
          return <Separator key={index} className="my-8 bg-white/10" />
      default:
        return null;
    }
  };

  const renderLayout = () => {
    switch (blueprint.layout) {
      case "card":
        return (
          <div className="flex justify-center items-center min-h-[50vh] p-4">
            <Card className="w-full max-w-md bg-card/50 backdrop-blur-xl border-white/10 shadow-2xl overflow-hidden">
              {/* Image blocks usually go first in cards */}
              {blueprint.data.filter(b => b.type === "image").map(renderBlock)}
              <CardHeader>
                <CardTitle className="text-2xl font-display text-glow">{blueprint.title}</CardTitle>
                <div className="flex gap-2 text-xs text-muted-foreground font-mono uppercase tracking-widest">
                   <span>v{blueprint.meta.version}</span>
                   <span>•</span>
                   <span>{blueprint.meta.author || "Anon"}</span>
                </div>
              </CardHeader>
              <CardContent>
                {blueprint.data.filter(b => b.type !== "image").map(renderBlock)}
                {/* Automatically append AI content if enabled but no placeholder exists */}
                {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
              </CardContent>
            </Card>
          </div>
        );
      
      case "newsfeed": {
        // Parse posts on first render
        useEffect(() => {
          if (posts.length === 0) {
            const parsedPosts: PostData[] = [];
            let currentPost = { author: "", content: "", metrics: "" };
            
            blueprint.data.forEach((block) => {
              if (block.type === "divider") {
                if (currentPost.author) {
                  const [likesStr, repliesStr, sharesStr] = currentPost.metrics.split(",");
                  const likes = parseInt(likesStr?.match(/\d+/)?.[0] || "0");
                  const replies = parseInt(repliesStr?.match(/\d+/)?.[0] || "0");
                  const shares = parseInt(sharesStr?.match(/\d+/)?.[0] || "0");
                  
                  parsedPosts.push({
                    id: `post-${parsedPosts.length}`,
                    author: currentPost.author,
                    content: currentPost.content,
                    likes,
                    replies,
                    shares,
                    liked: false,
                    expanded: false,
                    comments: [
                      { author: "Casey Dev", text: "This is incredible! 🚀" },
                      { author: "Morgan Tech", text: "The future is here." }
                    ]
                  });
                  currentPost = { author: "", content: "", metrics: "" };
                }
              } else if (block.type === "heading" && block.value?.includes("Post by")) {
                currentPost.author = block.value.replace("Post by ", "");
              } else if (block.type === "paragraph" && !currentPost.content) {
                currentPost.content = block.value || "";
              } else if (block.type === "list" && !currentPost.metrics) {
                currentPost.metrics = block.value || "";
              }
            });
            if (currentPost.author) {
              const [likesStr, repliesStr, sharesStr] = currentPost.metrics.split(",");
              const likes = parseInt(likesStr?.match(/\d+/)?.[0] || "0");
              const replies = parseInt(repliesStr?.match(/\d+/)?.[0] || "0");
              const shares = parseInt(sharesStr?.match(/\d+/)?.[0] || "0");
              
              parsedPosts.push({
                id: `post-${parsedPosts.length}`,
                author: currentPost.author,
                content: currentPost.content,
                likes,
                replies,
                shares,
                liked: false,
                expanded: false,
                comments: [
                  { author: "Alex Build", text: "Amazing work here!" },
                  { author: "Jordan Prototype", text: "Love this approach." }
                ]
              });
            }
            setPosts(parsedPosts);
          }
        }, [blueprint]);

        const toggleLike = (postId: string) => {
          setPosts(posts.map(p => 
            p.id === postId 
              ? { ...p, liked: !p.liked, likes: p.liked ? p.likes - 1 : p.likes + 1 }
              : p
          ));
        };

        const toggleExpanded = (postId: string) => {
          setPosts(posts.map(p => 
            p.id === postId ? { ...p, expanded: !p.expanded } : p
          ));
        };

        const addComment = (postId: string) => {
          if (!newCommentText[postId]?.trim()) return;
          
          setPosts(posts.map(p => 
            p.id === postId 
              ? {
                  ...p,
                  comments: [...p.comments, { author: "You", text: newCommentText[postId] }],
                  replies: p.replies + 1
                }
              : p
          ));
          setNewCommentText({ ...newCommentText, [postId]: "" });
        };

        return (
          <div className="max-w-2xl mx-auto p-6 md:p-8">
            <header className="mb-8 text-center">
              <Badge variant="outline" className="mb-4 border-secondary/50 text-secondary hover:bg-secondary/10">
                WebX Protocol // NEWSFEED
              </Badge>
              <h1 className="text-4xl font-display font-bold tracking-tight mb-3 text-glow">
                {blueprint.title}
              </h1>
              <p className="text-muted-foreground">{blueprint.data.find(b => b.type === "paragraph")?.value}</p>
            </header>

            <Separator className="my-8 bg-white/10" />

            <div className="space-y-4">
              {posts.map((post, idx) => (
                <motion.div
                  key={post.id}
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.05 }}
                >
                  <Card className="bg-white/5 border-white/10 hover:border-secondary/30 transition-all">
                    <CardContent className="p-6">
                      {/* Header */}
                      <div className="mb-4 pb-4 border-b border-white/10">
                        <h3 className="font-display font-bold text-lg text-secondary">{post.author}</h3>
                      </div>

                      {/* Content */}
                      <p className="text-foreground mb-6 leading-relaxed text-base">{post.content}</p>

                      {/* Engagement Buttons */}
                      <div className="flex gap-4 mb-6 pb-6 border-b border-white/10">
                        <button
                          onClick={() => toggleLike(post.id)}
                          className="flex items-center gap-2 text-sm transition-all hover:text-rose-400"
                        >
                          <Heart 
                            className={`w-5 h-5 transition-all ${post.liked ? 'fill-rose-400 text-rose-400' : 'text-muted-foreground'}`} 
                          />
                          <span className={post.liked ? 'text-rose-400 font-semibold' : 'text-muted-foreground'}>
                            {post.likes}
                          </span>
                        </button>

                        <button
                          onClick={() => toggleExpanded(post.id)}
                          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-secondary transition-all"
                        >
                          <MessageCircle className="w-5 h-5" />
                          <span>{post.replies}</span>
                        </button>

                        <button className="flex items-center gap-2 text-sm text-muted-foreground hover:text-secondary transition-all">
                          <Repeat2 className="w-5 h-5" />
                          <span>{post.shares}</span>
                        </button>
                      </div>

                      {/* Comments Section */}
                      {post.expanded && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: "auto" }}
                          exit={{ opacity: 0, height: 0 }}
                          className="space-y-4 mb-4"
                        >
                          <p className="text-xs font-mono text-primary/70 uppercase tracking-widest">Comments</p>
                          
                          {/* Existing Comments */}
                          <div className="space-y-3 pl-4 border-l border-white/10">
                            {post.comments.map((comment, i) => (
                              <div key={i} className="text-sm">
                                <span className="font-semibold text-secondary">{comment.author}</span>
                                <p className="text-muted-foreground mt-1">{comment.text}</p>
                              </div>
                            ))}
                          </div>

                          {/* Reply Input */}
                          <div className="flex gap-2 mt-4 pt-4 border-t border-white/10">
                            <Input
                              placeholder="Write a reply..."
                              value={newCommentText[post.id] || ""}
                              onChange={(e) => setNewCommentText({ ...newCommentText, [post.id]: e.target.value })}
                              onKeyDown={(e) => {
                                if (e.key === "Enter" && !e.shiftKey) {
                                  e.preventDefault();
                                  addComment(post.id);
                                }
                              }}
                              className="bg-white/5 border-white/10"
                            />
                            <Button
                              size="sm"
                              onClick={() => addComment(post.id)}
                              className="bg-secondary hover:bg-secondary/80"
                            >
                              <Send className="w-4 h-4" />
                            </Button>
                          </div>
                        </motion.div>
                      )}

                      {/* Expand Button */}
                      <button
                        onClick={() => toggleExpanded(post.id)}
                        className="flex items-center gap-2 text-xs text-primary/70 hover:text-primary transition-all"
                      >
                        {post.expanded ? (
                          <>
                            <ChevronUp className="w-4 h-4" /> Hide
                          </>
                        ) : (
                          <>
                            <ChevronDown className="w-4 h-4" /> Show Comments
                          </>
                        )}
                      </button>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>

            <Separator className="my-8 bg-white/10" />

            <footer className="flex flex-col md:flex-row justify-between items-center text-xs text-muted-foreground font-mono gap-4">
              <div className="flex items-center gap-2">
                <Cpu className="w-4 h-4" />
                Rendered Client-Side
              </div>
              <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10">
                <Fingerprint className="w-3 h-3 text-secondary" />
                <span>HASH: {blueprintHash}</span>
              </div>
              <div>WebX://{blueprint.meta.version}</div>
            </footer>
          </div>
        );
      }

      case "minimal":
          return (
              <div className="max-w-2xl mx-auto p-8 md:p-12 font-mono text-sm">
                  <div className="mb-12 border-b border-white/10 pb-4 flex justify-between items-baseline">
                    <h1 className="text-xl font-bold uppercase tracking-widest">{blueprint.title}</h1>
                    <span className="text-muted-foreground">{new Date(blueprint.meta.created).toLocaleDateString()}</span>
                  </div>
                  <div className="space-y-8">
                      {blueprint.data.map(renderBlock)}
                      {/* Automatically append AI content if enabled but no placeholder exists */}
                      {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
                  </div>
              </div>
          )

      case "article":
      default:
        return (
          <article className="max-w-3xl mx-auto px-6 py-12">
            <header className="mb-12 text-center">
               <Badge variant="outline" className="mb-4 border-secondary/50 text-secondary hover:bg-secondary/10">
                  WebX Protocol // {blueprint.layout.toUpperCase()}
               </Badge>
              <h1 className="text-4xl md:text-6xl font-display font-bold tracking-tight mb-6 text-glow">
                {blueprint.title}
              </h1>
              <div className="flex items-center justify-center gap-4 text-sm text-muted-foreground font-mono">
                <span className="flex items-center gap-1"><Terminal className="w-3 h-3" /> {blueprint.meta.author || "Unknown Author"}</span>
                <span className="w-1 h-1 bg-white/20 rounded-full" />
                <span>{new Date(blueprint.meta.created).toLocaleDateString()}</span>
              </div>
            </header>
            
            <div className="prose prose-invert prose-lg max-w-none">
              {blueprint.data.map(renderBlock)}
              {/* Automatically append AI content if enabled but no placeholder exists */}
              {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
            </div>

            <Separator className="my-12 bg-white/10" />
            
            <footer className="flex flex-col md:flex-row justify-between items-center text-xs text-muted-foreground font-mono gap-4">
                <div className="flex items-center gap-2">
                    <Cpu className="w-4 h-4" />
                    Rendered Client-Side
                </div>
                <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10" title="Deterministic Content Hash">
                    <Fingerprint className="w-3 h-3 text-secondary" />
                    <span>HASH: {blueprintHash}</span>
                </div>
                <div>
                    WebX://{blueprint.meta.version}
                </div>
            </footer>
          </article>
        );
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className={className}
    >
      {renderLayout()}
    </motion.div>
  );
}
