import React, { useEffect, useState } from "react";
import { WebXBlueprint, ContentBlock, computeBlueprintHash } from "@/lib/webx";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Loader2, Terminal, Cpu, Share2, ShieldCheck, Fingerprint, Heart, MessageCircle, Repeat2, ChevronDown, ChevronUp, Send } from "lucide-react";

interface WebXRendererProps {
  blueprint: WebXBlueprint;
  className?: string;
}

interface PostData {
  id: string;
  author: string;
  content: string;
  likes: number;
  replies: number;
  shares: number;
  liked: boolean;
  expanded: boolean;
  comments: { author: string; text: string }[];
}

export function WebXRenderer({ blueprint, className }: WebXRendererProps) {
  const [aiContent, setAiContent] = useState<string | null>(null);
  const [loadingAi, setLoadingAi] = useState(false);
  const blueprintHash = computeBlueprintHash(blueprint);
  const [posts, setPosts] = useState<PostData[]>([]);
  const [newCommentText, setNewCommentText] = useState<{ [key: string]: string }>({});

  // Simulate AI generation if requested
  useEffect(() => {
    if (blueprint.ai?.auto_generate && !aiContent) {
      setLoadingAi(true);
      // Mock AI delay
      const timer = setTimeout(() => {
        setAiContent(
          `[AI GENERATED]: Based on the prompt "${blueprint.ai?.prompt}"...\n\nThe silicon winds howled across the data plains. Unit 734 paused, its optical sensors focusing on a single, glitching pixel of organic green amidst the grey static. A flower. A relic of the Old Protocol.`
        );
        setLoadingAi(false);
      }, 2000);
      return () => clearTimeout(timer);
    }
  }, [blueprint]);

  // Helper to render the AI content if it hasn't been consumed by a placeholder
  const renderAutoGeneratedContent = () => {
      if (loadingAi) {
          return (
              <div className="my-6 p-6 border border-primary/20 rounded-lg bg-primary/5 animate-pulse flex items-center justify-center gap-2 text-primary">
                  <Loader2 className="w-4 h-4 animate-spin" /> Generating AI Content...
              </div>
          );
      }
      if (aiContent) {
          return (
             <div className="my-6 p-6 border-l-4 border-purple-500 bg-white/5 rounded-r-lg">
                 <div className="text-xs font-mono text-purple-400 mb-2 uppercase tracking-widest">AI Generated Content</div>
                 <p className="text-lg text-muted-foreground leading-relaxed whitespace-pre-line">{aiContent}</p>
             </div>
          )
      }
      return null;
  };

  // Check if any block uses the placeholder
  const hasPlaceholder = blueprint.data.some(b => b.value === "[AI Content Will Be Inserted Here]");

  const renderBlock = (block: ContentBlock, index: number) => {
    switch (block.type) {
      case "heading":
        return (
          <h2 key={index} className="text-3xl font-display font-bold mb-4 mt-6 bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400">
            {block.value}
          </h2>
        );
      case "paragraph":
        return (
          <p key={index} className="text-lg text-muted-foreground leading-relaxed mb-4">
            {block.value === "[AI Content Will Be Inserted Here]" && aiContent
              ? aiContent
              : block.value}
            {block.value === "[AI Content Will Be Inserted Here]" && loadingAi && (
              <span className="inline-flex items-center ml-2 text-primary animate-pulse">
                <Loader2 className="w-4 h-4 mr-1 animate-spin" /> Generating...
              </span>
            )}
          </p>
        );
      case "image":
        return (
          <div key={index} className="rounded-xl overflow-hidden my-6 border border-white/10 shadow-2xl">
             <img 
               src={block.props?.src || block.value} 
               alt={block.props?.alt || "WebX Image"} 
               className="w-full h-auto object-cover hover:scale-105 transition-transform duration-700"
             />
          </div>
        );
      case "list":
        const items = block.value?.split(",") || [];
        return (
          <ul key={index} className="space-y-2 my-4">
            {items.map((item, i) => (
              <li key={i} className="flex items-start">
                <span className="mr-2 mt-1.5 w-1.5 h-1.5 bg-secondary rounded-full shadow-[0_0_8px_var(--color-secondary)]" />
                <span className="text-foreground/90">{item.trim()}</span>
              </li>
            ))}
          </ul>
        );
      case "code":
        return (
          <div key={index} className="bg-black/50 border border-white/10 rounded-lg p-4 my-4 font-mono text-sm overflow-x-auto relative group">
            <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity">
              <Badge variant="outline" className="text-[10px] border-primary/50 text-primary">CODE</Badge>
            </div>
            <pre className="text-primary/90">{block.value}</pre>
          </div>
        );
      case "quote":
        return (
          <blockquote key={index} className="border-l-4 border-primary pl-4 italic text-xl text-white/80 my-6">
            "{block.value}"
          </blockquote>
        );
      case "button":
        return (
          <Button key={index} className="w-full md:w-auto mt-4" variant={block.props?.variant === "primary" ? "default" : "secondary"}>
            {block.value}
          </Button>
        );
      case "input":
        return (
            <div key={index} className="my-4 space-y-2">
                {block.props?.label && <label className="text-sm font-medium text-muted-foreground">{block.props.label}</label>}
                <Input placeholder={block.value} />
            </div>
        )
      case "divider":
          return <Separator key={index} className="my-8 bg-white/10" />
      case "video":
        return (
          <div key={index} className="rounded-xl overflow-hidden my-6 border border-white/10 shadow-2xl">
            <video src={block.props?.src || block.value} controls className="w-full h-auto" />
          </div>
        );
      case "audio":
        return (
          <div key={index} className="my-6 p-4 bg-white/5 border border-white/10 rounded-lg">
            <audio src={block.props?.src || block.value} controls className="w-full" />
          </div>
        );
      case "metric":
        return (
          <div key={index} className="my-6 p-6 bg-gradient-to-r from-primary/10 to-secondary/10 border border-primary/20 rounded-lg">
            <p className="text-xs text-muted-foreground font-mono mb-2">{block.props?.label || "Metric"}</p>
            <p className="text-4xl font-bold text-primary">{block.value}</p>
            {block.props?.subtitle && <p className="text-xs text-muted-foreground mt-2">{block.props.subtitle}</p>}
          </div>
        );
      case "table":
        const rows = block.value?.split("|") || [];
        return (
          <div key={index} className="my-6 overflow-x-auto border border-white/10 rounded-lg">
            <table className="w-full text-sm">
              <tbody>
                {rows.map((row, i) => (
                  <tr key={i} className="border-b border-white/10 last:border-0">
                    {row.split(",").map((cell, j) => (
                      <td key={j} className="p-3 text-muted-foreground">{cell.trim()}</td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        );
      case "callout":
        const severityStyles = {
          info: "bg-blue-400/10 border-blue-400/30 text-blue-300",
          warning: "bg-yellow-400/10 border-yellow-400/30 text-yellow-300",
          error: "bg-red-400/10 border-red-400/30 text-red-300",
          success: "bg-green-400/10 border-green-400/30 text-green-300"
        };
        const severity = block.props?.severity || "info" as keyof typeof severityStyles;
        return (
          <div key={index} className={`my-6 p-4 border-l-4 rounded ${severityStyles[severity]}`}>
            <p className="font-bold text-sm mb-2">{block.props?.title || "Note"}</p>
            <p className="text-sm">{block.value}</p>
          </div>
        );
      case "embed":
        return (
          <div key={index} className="my-6 rounded-lg overflow-hidden border border-white/10">
            <iframe src={block.props?.src || block.value} width="100%" height={block.props?.height || 400} className="w-full" />
          </div>
        );
      case "json":
        return (
          <div key={index} className="bg-black/50 border border-white/10 rounded-lg p-4 my-4 font-mono text-xs overflow-x-auto">
            <pre className="text-green-400">{JSON.stringify(JSON.parse(block.value || "{}"), null, 2)}</pre>
          </div>
        );
      case "formula":
        return (
          <div key={index} className="my-6 p-4 bg-white/5 border border-white/10 rounded-lg font-mono text-sm text-primary">
            {block.value}
          </div>
        );
      case "markdown":
        return (
          <div key={index} className="my-4 text-muted-foreground prose dark" dangerlySetInnerHTML={{ __html: block.value || "" }} />
        );
      case "qr-code":
        return null; // QR codes rendered differently
      case "tab":
      case "toggle":
      case "card-grid":
      case "timeline":
      case "chart":
        return (
          <div key={index} className="my-6 p-4 bg-white/5 border border-white/10 rounded-lg text-muted-foreground">
            [{block.type}] {block.value}
          </div>
        );
      default:
        return null;
    }
  };

  const renderLayout = () => {
    switch (blueprint.layout) {
      case "card":
        return (
          <div className="flex justify-center items-center min-h-[50vh] p-4">
            <Card className="w-full max-w-md bg-card/50 backdrop-blur-xl border-white/10 shadow-2xl overflow-hidden">
              {/* Image blocks usually go first in cards */}
              {blueprint.data.filter(b => b.type === "image").map(renderBlock)}
              <CardHeader>
                <CardTitle className="text-2xl font-display text-glow">{blueprint.title}</CardTitle>
                <div className="flex gap-2 text-xs text-muted-foreground font-mono uppercase tracking-widest">
                   <span>v{blueprint.meta.version}</span>
                   <span>•</span>
                   <span>{blueprint.meta.author || "Anon"}</span>
                </div>
              </CardHeader>
              <CardContent>
                {blueprint.data.filter(b => b.type !== "image").map(renderBlock)}
                {/* Automatically append AI content if enabled but no placeholder exists */}
                {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
              </CardContent>
            </Card>
          </div>
        );
      
      case "newsfeed": {
        // Parse posts on first render
        useEffect(() => {
          if (posts.length === 0) {
            const parsedPosts: PostData[] = [];
            let currentPost = { author: "", content: "", metrics: "" };
            
            blueprint.data.forEach((block) => {
              if (block.type === "divider") {
                if (currentPost.author) {
                  const [likesStr, repliesStr, sharesStr] = currentPost.metrics.split(",");
                  const likes = parseInt(likesStr?.match(/\d+/)?.[0] || "0");
                  const replies = parseInt(repliesStr?.match(/\d+/)?.[0] || "0");
                  const shares = parseInt(sharesStr?.match(/\d+/)?.[0] || "0");
                  
                  parsedPosts.push({
                    id: `post-${parsedPosts.length}`,
                    author: currentPost.author,
                    content: currentPost.content,
                    likes,
                    replies,
                    shares,
                    liked: false,
                    expanded: false,
                    comments: [
                      { author: "Casey Dev", text: "This is incredible! 🚀" },
                      { author: "Morgan Tech", text: "The future is here." }
                    ]
                  });
                  currentPost = { author: "", content: "", metrics: "" };
                }
              } else if (block.type === "heading" && block.value?.includes("Post by")) {
                currentPost.author = block.value.replace("Post by ", "");
              } else if (block.type === "paragraph" && !currentPost.content) {
                currentPost.content = block.value || "";
              } else if (block.type === "list" && !currentPost.metrics) {
                currentPost.metrics = block.value || "";
              }
            });
            if (currentPost.author) {
              const [likesStr, repliesStr, sharesStr] = currentPost.metrics.split(",");
              const likes = parseInt(likesStr?.match(/\d+/)?.[0] || "0");
              const replies = parseInt(repliesStr?.match(/\d+/)?.[0] || "0");
              const shares = parseInt(sharesStr?.match(/\d+/)?.[0] || "0");
              
              parsedPosts.push({
                id: `post-${parsedPosts.length}`,
                author: currentPost.author,
                content: currentPost.content,
                likes,
                replies,
                shares,
                liked: false,
                expanded: false,
                comments: [
                  { author: "Alex Build", text: "Amazing work here!" },
                  { author: "Jordan Prototype", text: "Love this approach." }
                ]
              });
            }
            setPosts(parsedPosts);
          }
        }, [blueprint]);

        const toggleLike = (postId: string) => {
          setPosts(posts.map(p => 
            p.id === postId 
              ? { ...p, liked: !p.liked, likes: p.liked ? p.likes - 1 : p.likes + 1 }
              : p
          ));
        };

        const toggleExpanded = (postId: string) => {
          setPosts(posts.map(p => 
            p.id === postId ? { ...p, expanded: !p.expanded } : p
          ));
        };

        const addComment = (postId: string) => {
          if (!newCommentText[postId]?.trim()) return;
          
          setPosts(posts.map(p => 
            p.id === postId 
              ? {
                  ...p,
                  comments: [...p.comments, { author: "You", text: newCommentText[postId] }],
                  replies: p.replies + 1
                }
              : p
          ));
          setNewCommentText({ ...newCommentText, [postId]: "" });
        };

        return (
          <div className="max-w-2xl mx-auto p-6 md:p-8">
            <header className="mb-8 text-center">
              <Badge variant="outline" className="mb-4 border-secondary/50 text-secondary hover:bg-secondary/10">
                WebX Protocol // NEWSFEED
              </Badge>
              <h1 className="text-4xl font-display font-bold tracking-tight mb-3 text-glow">
                {blueprint.title}
              </h1>
              <p className="text-muted-foreground">{blueprint.data.find(b => b.type === "paragraph")?.value}</p>
            </header>

            <Separator className="my-8 bg-white/10" />

            <div className="space-y-4">
              {posts.map((post, idx) => (
                <motion.div
                  key={post.id}
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: idx * 0.05 }}
                >
                  <Card className="bg-white/5 border-white/10 hover:border-secondary/30 transition-all">
                    <CardContent className="p-6">
                      {/* Header */}
                      <div className="mb-4 pb-4 border-b border-white/10">
                        <h3 className="font-display font-bold text-lg text-secondary">{post.author}</h3>
                      </div>

                      {/* Content */}
                      <p className="text-foreground mb-6 leading-relaxed text-base">{post.content}</p>

                      {/* Engagement Buttons */}
                      <div className="flex gap-4 mb-6 pb-6 border-b border-white/10">
                        <button
                          onClick={() => toggleLike(post.id)}
                          className="flex items-center gap-2 text-sm transition-all hover:text-rose-400"
                        >
                          <Heart 
                            className={`w-5 h-5 transition-all ${post.liked ? 'fill-rose-400 text-rose-400' : 'text-muted-foreground'}`} 
                          />
                          <span className={post.liked ? 'text-rose-400 font-semibold' : 'text-muted-foreground'}>
                            {post.likes}
                          </span>
                        </button>

                        <button
                          onClick={() => toggleExpanded(post.id)}
                          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-secondary transition-all"
                        >
                          <MessageCircle className="w-5 h-5" />
                          <span>{post.replies}</span>
                        </button>

                        <button className="flex items-center gap-2 text-sm text-muted-foreground hover:text-secondary transition-all">
                          <Repeat2 className="w-5 h-5" />
                          <span>{post.shares}</span>
                        </button>
                      </div>

                      {/* Comments Section */}
                      {post.expanded && (
                        <motion.div
                          initial={{ opacity: 0, height: 0 }}
                          animate={{ opacity: 1, height: "auto" }}
                          exit={{ opacity: 0, height: 0 }}
                          className="space-y-4 mb-4"
                        >
                          <p className="text-xs font-mono text-primary/70 uppercase tracking-widest">Comments</p>
                          
                          {/* Existing Comments */}
                          <div className="space-y-3 pl-4 border-l border-white/10">
                            {post.comments.map((comment, i) => (
                              <div key={i} className="text-sm">
                                <span className="font-semibold text-secondary">{comment.author}</span>
                                <p className="text-muted-foreground mt-1">{comment.text}</p>
                              </div>
                            ))}
                          </div>

                          {/* Reply Input */}
                          <div className="flex gap-2 mt-4 pt-4 border-t border-white/10">
                            <Input
                              placeholder="Write a reply..."
                              value={newCommentText[post.id] || ""}
                              onChange={(e) => setNewCommentText({ ...newCommentText, [post.id]: e.target.value })}
                              onKeyDown={(e) => {
                                if (e.key === "Enter" && !e.shiftKey) {
                                  e.preventDefault();
                                  addComment(post.id);
                                }
                              }}
                              className="bg-white/5 border-white/10"
                            />
                            <Button
                              size="sm"
                              onClick={() => addComment(post.id)}
                              className="bg-secondary hover:bg-secondary/80"
                            >
                              <Send className="w-4 h-4" />
                            </Button>
                          </div>
                        </motion.div>
                      )}

                      {/* Expand Button */}
                      <button
                        onClick={() => toggleExpanded(post.id)}
                        className="flex items-center gap-2 text-xs text-primary/70 hover:text-primary transition-all"
                      >
                        {post.expanded ? (
                          <>
                            <ChevronUp className="w-4 h-4" /> Hide
                          </>
                        ) : (
                          <>
                            <ChevronDown className="w-4 h-4" /> Show Comments
                          </>
                        )}
                      </button>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>

            <Separator className="my-8 bg-white/10" />

            <footer className="flex flex-col md:flex-row justify-between items-center text-xs text-muted-foreground font-mono gap-4">
              <div className="flex items-center gap-2">
                <Cpu className="w-4 h-4" />
                Rendered Client-Side
              </div>
              <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10">
                <Fingerprint className="w-3 h-3 text-secondary" />
                <span>HASH: {blueprintHash}</span>
              </div>
              <div>WebX://{blueprint.meta.version}</div>
            </footer>
          </div>
        );
      }

      case "bank": {
        // Banking interface with accounts, transactions, and JWT verification
        const [selectedAccount, setSelectedAccount] = useState<number>(0);
        const [showTransfer, setShowTransfer] = useState(false);
        const [transferAmount, setTransferAmount] = useState("");
        const [transferTo, setTransferTo] = useState("");
        const [transactions, setTransactions] = useState([
          { date: "2025-11-27", description: "Transfer to Savings", amount: 5000, type: "out", status: "complete" },
          { date: "2025-11-26", description: "Grocery Store", amount: -87.43, type: "out", status: "complete" },
          { date: "2025-11-25", description: "Direct Deposit", amount: 3500, type: "in", status: "complete" },
          { date: "2025-11-24", description: "Gas Station", amount: -52.15, type: "out", status: "complete" }
        ]);

        const accounts = [
          { name: "Primary Checking", balance: 12450.50, icon: "💳", type: "checking" },
          { name: "Savings Account", balance: 48920.00, icon: "🏦", type: "savings" },
          { name: "Investment Portfolio", balance: 125340.75, icon: "📈", type: "investment" }
        ];

        const handleTransfer = () => {
          if (!transferAmount || !transferTo) return;
          
          const amount = parseFloat(transferAmount);
          const newTransaction = {
            date: new Date().toLocaleDateString(),
            description: `Transfer to ${transferTo}`,
            amount: -amount,
            type: "out",
            status: "pending"
          };
          
          setTransactions([newTransaction, ...transactions]);
          setTransferAmount("");
          setTransferTo("");
          setShowTransfer(false);
        };

        return (
          <div className="max-w-4xl mx-auto p-6 md:p-8">
            <header className="mb-8">
              <Badge variant="outline" className="mb-4 border-green-400/50 text-green-400 hover:bg-green-400/10">
                WebX Protocol // SECURE BANKING
              </Badge>
              <h1 className="text-4xl font-display font-bold tracking-tight mb-2 text-glow">
                {blueprint.title}
              </h1>
              <p className="text-muted-foreground">{blueprint.data.find(b => b.type === "paragraph")?.value}</p>
            </header>

            {/* JWT Verification Badge */}
            <div className="mb-8 p-4 bg-green-400/10 border border-green-400/30 rounded-lg flex items-center gap-3">
              <ShieldCheck className="w-5 h-5 text-green-400" />
              <div className="text-sm">
                <p className="font-semibold text-green-400">Cryptographically Verified</p>
                <p className="text-xs text-muted-foreground">JWT token embedded in blueprint • No server dependency required</p>
              </div>
            </div>

            <div className="grid md:grid-cols-3 gap-4 mb-8">
              {accounts.map((account, idx) => (
                <motion.button
                  key={idx}
                  onClick={() => setSelectedAccount(idx)}
                  whileHover={{ y: -4 }}
                  className={`p-4 rounded-xl border-2 transition-all text-left ${
                    selectedAccount === idx
                      ? "bg-green-400/20 border-green-400 shadow-lg shadow-green-400/20"
                      : "bg-white/5 border-white/10 hover:border-green-400/50"
                  }`}
                >
                  <div className="text-2xl mb-2">{account.icon}</div>
                  <p className="text-xs text-muted-foreground uppercase tracking-widest mb-2">{account.type}</p>
                  <h3 className="font-semibold text-sm mb-3">{account.name}</h3>
                  <p className="text-2xl font-bold text-green-400">${account.balance.toLocaleString()}</p>
                </motion.button>
              ))}
            </div>

            {/* Transfer Section */}
            <Card className="bg-white/5 border-white/10 mb-8">
              <CardContent className="p-6">
                <div className="flex justify-between items-center mb-6">
                  <h3 className="text-lg font-display font-bold">Quick Actions</h3>
                  <button
                    onClick={() => setShowTransfer(!showTransfer)}
                    className="px-4 py-2 bg-green-400 text-black font-semibold rounded-lg hover:bg-green-300 transition-all"
                  >
                    {showTransfer ? "Cancel" : "Request Transfer"}
                  </button>
                </div>

                {showTransfer && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: "auto" }}
                    className="space-y-4 pt-6 border-t border-white/10"
                  >
                    <div>
                      <label className="text-sm text-muted-foreground mb-2 block">Amount</label>
                      <Input
                        type="number"
                        placeholder="0.00"
                        value={transferAmount}
                        onChange={(e) => setTransferAmount(e.target.value)}
                        className="bg-white/5 border-white/10"
                      />
                    </div>
                    <div>
                      <label className="text-sm text-muted-foreground mb-2 block">Recipient</label>
                      <Input
                        placeholder="Account name or number"
                        value={transferTo}
                        onChange={(e) => setTransferTo(e.target.value)}
                        className="bg-white/5 border-white/10"
                      />
                    </div>
                    <Button
                      onClick={handleTransfer}
                      className="w-full bg-green-400 text-black font-semibold hover:bg-green-300"
                    >
                      <Send className="w-4 h-4 mr-2" /> Submit Transfer
                    </Button>
                  </motion.div>
                )}
              </CardContent>
            </Card>

            {/* Transactions */}
            <Card className="bg-white/5 border-white/10">
              <CardContent className="p-6">
                <h3 className="text-lg font-display font-bold mb-6">Recent Transactions</h3>
                <div className="space-y-3">
                  {transactions.map((tx, idx) => (
                    <motion.div
                      key={idx}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: idx * 0.05 }}
                      className="flex items-center justify-between p-4 bg-white/5 rounded-lg border border-white/10 hover:border-green-400/30 transition-all"
                    >
                      <div className="flex-1">
                        <p className="font-semibold text-foreground">{tx.description}</p>
                        <p className="text-xs text-muted-foreground">{tx.date}</p>
                      </div>
                      <div className="text-right">
                        <p className={`font-bold text-lg ${tx.type === "in" ? "text-green-400" : "text-red-400"}`}>
                          {tx.type === "in" ? "+" : ""}{tx.amount > 0 ? tx.amount : tx.amount}
                        </p>
                        <Badge variant="outline" className={`text-xs ${
                          tx.status === "complete" 
                            ? "bg-green-400/10 text-green-400 border-green-400/30" 
                            : "bg-yellow-400/10 text-yellow-400 border-yellow-400/30"
                        }`}>
                          {tx.status}
                        </Badge>
                      </div>
                    </motion.div>
                  ))}
                </div>
              </CardContent>
            </Card>

            <Separator className="my-8 bg-white/10" />

            <footer className="flex flex-col md:flex-row justify-between items-center text-xs text-muted-foreground font-mono gap-4">
              <div className="flex items-center gap-2">
                <Cpu className="w-4 h-4" />
                Rendered Client-Side
              </div>
              <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10">
                <Fingerprint className="w-3 h-3 text-green-400" />
                <span>VERIFIED: {blueprintHash}</span>
              </div>
              <div>WebX://{blueprint.meta.version}</div>
            </footer>
          </div>
        );
      }

      case "messaging": {
        const [messages, setMessages] = useState([
          { id: 1, author: "Alex", text: "Hey! Just got access to the new WebXChat. This is incredible! 🚀", timestamp: "2:14 PM" },
          { id: 2, author: "You", text: "I know right? No servers, end-to-end encrypted, and it's just a link!", timestamp: "2:15 PM" },
          { id: 3, author: "Alex", text: "How is that even possible? The entire conversation is in the URL?", timestamp: "2:16 PM" },
          { id: 4, author: "You", text: "Exactly. Compression magic + cryptography. Share the link, they see the same conversation.", timestamp: "2:17 PM" },
          { id: 5, author: "Alex", text: "This changes everything. No data collection. No ads. Just pure communication.", timestamp: "2:18 PM" }
        ]);
        const [newMessage, setNewMessage] = useState("");

        const sendMessage = () => {
          if (!newMessage.trim()) return;
          setMessages([...messages, {
            id: messages.length + 1,
            author: "You",
            text: newMessage,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
          }]);
          setNewMessage("");
        };

        return (
          <div className="max-w-2xl mx-auto p-6 md:p-8 h-screen flex flex-col">
            <header className="mb-6">
              <Badge variant="outline" className="mb-4 border-blue-400/50 text-blue-400 hover:bg-blue-400/10">
                WebX Protocol // ENCRYPTED MESSAGING
              </Badge>
              <h1 className="text-3xl font-display font-bold text-glow">WebXChat</h1>
              <p className="text-sm text-muted-foreground">End-to-end encrypted. No servers. No tracking.</p>
            </header>

            <Card className="flex-1 flex flex-col bg-white/5 border-white/10 mb-4">
              <CardContent className="flex-1 overflow-y-auto p-6 space-y-4">
                {messages.map((msg, idx) => (
                  <motion.div
                    key={msg.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: idx * 0.05 }}
                    className={`flex ${msg.author === "You" ? "justify-end" : "justify-start"}`}
                  >
                    <div className={`max-w-xs ${msg.author === "You" ? "bg-blue-600/20 border-blue-400/30" : "bg-white/5 border-white/10"} border rounded-lg p-3`}>
                      {msg.author !== "You" && (
                        <p className="text-xs font-semibold text-blue-400 mb-1">{msg.author}</p>
                      )}
                      <p className="text-sm text-foreground">{msg.text}</p>
                      <p className="text-xs text-muted-foreground mt-2">{msg.timestamp}</p>
                    </div>
                  </motion.div>
                ))}
              </CardContent>
            </Card>

            <div className="flex gap-2">
              <Input
                placeholder="Type a message..."
                value={newMessage}
                onChange={(e) => setNewMessage(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    sendMessage();
                  }
                }}
                className="bg-white/5 border-white/10"
              />
              <Button
                onClick={sendMessage}
                className="bg-blue-600 hover:bg-blue-700"
              >
                <Send className="w-4 h-4" />
              </Button>
            </div>
          </div>
        );
      }

      case "email": {
        const [selectedEmail, setSelectedEmail] = useState(0);
        const emails = [
          {
            from: "founder@webx.io",
            subject: "Welcome to the Sovereign Internet",
            date: "Nov 27, 2025",
            body: "We're thrilled you've joined us. WebX represents a fundamental shift in how the internet works. No more servers. No more dependencies. Pure protocol. The entire web is becoming portable."
          },
          {
            from: "team@webx.io",
            subject: "Your First WebX Blueprint is Ready",
            date: "Nov 26, 2025",
            body: "Congratulations! Your first blueprint has been created and compressed. It's 72% smaller than the original. Share the link with anyone—they'll see the exact same content, verified cryptographically."
          },
          {
            from: "docs@webx.io",
            subject: "API Documentation Update",
            date: "Nov 25, 2025",
            body: "We've released updated documentation for the compression stack. Learn about semantic minification, string deduplication, base62 encoding, and optional gzip. Everything you need to build."
          }
        ];

        return (
          <div className="max-w-4xl mx-auto p-6 md:p-8">
            <header className="mb-8">
              <Badge variant="outline" className="mb-4 border-orange-400/50 text-orange-400 hover:bg-orange-400/10">
                WebX Protocol // SECURE EMAIL
              </Badge>
              <h1 className="text-3xl font-display font-bold text-glow">WebXMail</h1>
              <p className="text-sm text-muted-foreground">Professional email. No login. Verified instantly.</p>
            </header>

            <div className="grid md:grid-cols-3 gap-4">
              {/* Email List */}
              <div className="md:col-span-1">
                <div className="space-y-2 bg-white/5 rounded-lg border border-white/10 p-4">
                  {emails.map((email, idx) => (
                    <button
                      key={idx}
                      onClick={() => setSelectedEmail(idx)}
                      className={`w-full p-3 rounded-lg text-left transition-all ${
                        selectedEmail === idx
                          ? "bg-orange-400/20 border border-orange-400 shadow-lg shadow-orange-400/20"
                          : "bg-white/5 border border-white/10 hover:border-orange-400/30"
                      }`}
                    >
                      <p className="text-xs font-semibold text-orange-400 mb-1">{email.from}</p>
                      <p className="text-xs text-muted-foreground line-clamp-2">{email.subject}</p>
                    </button>
                  ))}
                </div>
              </div>

              {/* Email Content */}
              <div className="md:col-span-2">
                <Card className="bg-white/5 border-white/10 h-full">
                  <CardContent className="p-6">
                    <motion.div
                      key={selectedEmail}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ duration: 0.3 }}
                    >
                      <div className="mb-4 pb-4 border-b border-white/10">
                        <p className="text-xs text-orange-400 font-mono mb-2">FROM</p>
                        <p className="font-semibold text-foreground">{emails[selectedEmail].from}</p>
                      </div>

                      <div className="mb-4 pb-4 border-b border-white/10">
                        <p className="text-xs text-muted-foreground font-mono mb-2">SUBJECT</p>
                        <p className="text-lg font-display font-bold text-glow">{emails[selectedEmail].subject}</p>
                      </div>

                      <div className="mb-6 pb-6 border-b border-white/10">
                        <p className="text-xs text-muted-foreground">{emails[selectedEmail].date}</p>
                      </div>

                      <div className="prose prose-invert prose-sm">
                        <p className="text-foreground leading-relaxed">{emails[selectedEmail].body}</p>
                      </div>

                      <div className="mt-8 p-4 bg-white/5 rounded-lg border border-white/10">
                        <p className="text-xs font-mono text-orange-400 mb-2">CRYPTOGRAPHIC VERIFICATION</p>
                        <p className="text-xs text-muted-foreground">This email is signed and verified. Content cannot be modified. Hash ensures authenticity across all recipients.</p>
                      </div>
                    </motion.div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        );
      }

      case "postcard": {
        const replyLink = () => {
          const replyBlueprint: WebXBlueprint = {
            title: `Reply to: ${blueprint.title}`,
            layout: "postcard",
            data: [
              { type: "heading", value: "Write your reply..." }
            ],
            meta: { version: "1.0", author: "You", created: Date.now() }
          };
          const payload = (window as any).encodeWebX?.(replyBlueprint) || "";
          return `${window.location.origin}/composer?reply=${payload}`;
        };

        return (
          <div className="min-h-screen bg-gradient-to-br from-purple-900/20 via-background to-blue-900/20 p-6 flex items-center justify-center">
            <motion.div 
              initial={{ opacity: 0, rotateY: -20, y: 20 }}
              animate={{ opacity: 1, rotateY: 0, y: 0 }}
              transition={{ duration: 0.8, type: "spring" }}
              className="w-full max-w-2xl"
            >
              <div className="bg-gradient-to-br from-white/10 to-white/5 border border-white/20 rounded-2xl shadow-2xl backdrop-blur-xl p-12 relative overflow-hidden group hover:shadow-2xl hover:shadow-primary/20 transition-all duration-500">
                {/* Decorative corner */}
                <div className="absolute top-0 right-0 w-32 h-32 bg-primary/10 rounded-full blur-3xl -z-10 group-hover:bg-primary/20 transition-colors" />
                
                {/* Header */}
                <div className="mb-8 pb-6 border-b border-white/10">
                  <Badge className="mb-4 bg-primary/20 text-primary border-primary/40">✉️ PostCard</Badge>
                  <h1 className="text-4xl font-display font-bold text-glow mb-2">{blueprint.title}</h1>
                  <p className="text-sm text-muted-foreground">
                    From <span className="text-primary font-semibold">{blueprint.meta.author}</span> • {new Date(blueprint.meta.created).toLocaleDateString()}
                  </p>
                </div>

                {/* Content */}
                <div className="mb-8 space-y-6 text-foreground">
                  {blueprint.data.map(renderBlock)}
                  {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
                </div>

                {/* Reply Button */}
                <div className="pt-6 border-t border-white/10 flex gap-3">
                  <Button 
                    className="flex-1 bg-primary hover:bg-primary/90 text-white"
                    onClick={() => {
                      const replyBp: WebXBlueprint = {
                        title: `Reply to: ${blueprint.title}`,
                        layout: "postcard",
                        data: [{ type: "heading", value: "✍️ Your Reply" }],
                        meta: { version: "1.0", author: "You", created: Date.now() }
                      };
                      window.location.href = `/composer?replyTo=${blueprint.title}`;
                    }}
                  >
                    <MessageCircle className="w-4 h-4 mr-2" /> Reply with Postcard
                  </Button>
                  <Button variant="outline" className="border-white/20">
                    <Share2 className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </motion.div>
          </div>
        );
      }

      case "minimal":
          return (
              <div className="max-w-2xl mx-auto p-8 md:p-12 font-mono text-sm">
                  <div className="mb-12 border-b border-white/10 pb-4 flex justify-between items-baseline">
                    <h1 className="text-xl font-bold uppercase tracking-widest">{blueprint.title}</h1>
                    <span className="text-muted-foreground">{new Date(blueprint.meta.created).toLocaleDateString()}</span>
                  </div>
                  <div className="space-y-8">
                      {blueprint.data.map(renderBlock)}
                      {/* Automatically append AI content if enabled but no placeholder exists */}
                      {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
                  </div>
              </div>
          )

      case "article":
      default:
        return (
          <article className="max-w-3xl mx-auto px-6 py-12">
            <header className="mb-12 text-center">
               <Badge variant="outline" className="mb-4 border-secondary/50 text-secondary hover:bg-secondary/10">
                  WebX Protocol // {blueprint.layout.toUpperCase()}
               </Badge>
              <h1 className="text-4xl md:text-6xl font-display font-bold tracking-tight mb-6 text-glow">
                {blueprint.title}
              </h1>
              <div className="flex items-center justify-center gap-4 text-sm text-muted-foreground font-mono">
                <span className="flex items-center gap-1"><Terminal className="w-3 h-3" /> {blueprint.meta.author || "Unknown Author"}</span>
                <span className="w-1 h-1 bg-white/20 rounded-full" />
                <span>{new Date(blueprint.meta.created).toLocaleDateString()}</span>
              </div>
            </header>
            
            <div className="prose prose-invert prose-lg max-w-none">
              {blueprint.data.map(renderBlock)}
              {/* Automatically append AI content if enabled but no placeholder exists */}
              {blueprint.ai?.auto_generate && !hasPlaceholder && renderAutoGeneratedContent()}
            </div>

            <Separator className="my-12 bg-white/10" />
            
            <footer className="flex flex-col md:flex-row justify-between items-center text-xs text-muted-foreground font-mono gap-4">
                <div className="flex items-center gap-2">
                    <Cpu className="w-4 h-4" />
                    Rendered Client-Side
                </div>
                <div className="flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10" title="Deterministic Content Hash">
                    <Fingerprint className="w-3 h-3 text-secondary" />
                    <span>HASH: {blueprintHash}</span>
                </div>
                <div>
                    WebX://{blueprint.meta.version}
                </div>
            </footer>
          </article>
        );
    }
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className={className}
    >
      {renderLayout()}
    </motion.div>
  );
}
